services:
  smsget-dlr-report:
    image: aroksetx/smsget-dlr-report:latest
    container_name: smsget-dlr-report
    restart: unless-stopped
    ports:
      - "2776:2776"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
